import 'dart:convert';
import 'dart:io';

import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;
import 'package:yaml/yaml.dart';

/// Case-insensitive markers that generators write into a file's leading comment
/// block. Kept tight so a hand-written note is unlikely to trip them:
///   * `GENERATED CODE - DO NOT MODIFY` (source_gen, protoc, build_runner)
///   * `DO NOT EDIT` (many templating generators)
///   * `AUTO-GENERATED` / `AUTOGENERATED`
const _generatedHeaderMarkers = <String>[
  'GENERATED CODE - DO NOT MODIFY',
  'DO NOT EDIT',
  'AUTO-GENERATED',
  'AUTOGENERATED',
];

/// Returns true if the leading comment block of [filePath] carries a
/// generated-code marker (`GENERATED CODE - DO NOT MODIFY BY HAND`, `DO NOT
/// EDIT`, …). Catches generators that write plain file names with no known
/// suffix (e.g. `build_runner` outputs a hand-picked file name).
///
/// Only the top of the file is inspected: scanning stops at the first line that
/// is neither blank nor a comment, since these markers always sit above any real
/// declaration. A missing or unreadable file is treated as not generated, so the
/// synthetic paths the directory walk probes with never trip it.
bool hasGeneratedHeader(String filePath) {
  final head = _readHead(filePath);
  if (head == null) return false;

  var inBlockComment = false;
  for (final rawLine in const LineSplitter().convert(head)) {
    final line = rawLine.trim();
    if (line.isEmpty) continue;

    if (inBlockComment) {
      if (_hasGeneratedMarker(line)) return true;
      if (line.contains('*/')) inBlockComment = false;
      continue;
    }
    if (line.startsWith('//')) {
      if (_hasGeneratedMarker(line)) return true;
      continue;
    }
    if (line.startsWith('/*')) {
      if (_hasGeneratedMarker(line)) return true;
      if (!line.contains('*/')) inBlockComment = true;
      continue;
    }
    // First real declaration or directive: markers only live above it.
    return false;
  }
  return false;
}

/// Returns true if [filePath] is a generated file that should be skipped.
///
/// Matches common Dart code-generation suffixes and the `build/` output directory.
bool isGeneratedFile(String filePath) {
  final name = p.basename(filePath);
  if (name.endsWith('.g.dart')) return true;
  if (name.endsWith('.freezed.dart')) return true;
  if (name.endsWith('.gen.dart')) return true;
  if (name.endsWith('.gr.dart')) return true;
  if (name.endsWith('.pb.dart')) return true;
  if (name.endsWith('.pbenum.dart')) return true;
  return p.split(filePath).contains('build');
}

/// Reads the `analyzer: exclude:` list from [projectPath]/analysis_options.yaml.
List<String> readAnalysisOptionsExcludes(String projectPath) {
  final file = File(p.join(projectPath, 'analysis_options.yaml'));
  if (!file.existsSync()) return const [];
  final dynamic yaml = loadYaml(file.readAsStringSync());
  if (yaml is! YamlMap) return const [];
  final dynamic analyzer = yaml['analyzer'];
  if (analyzer is! YamlMap) return const [];
  final dynamic exclude = analyzer['exclude'];
  if (exclude is! YamlList) return const [];
  return [
    for (final dynamic e in exclude)
      if (e is String) e,
  ];
}

/// Reads [projectPath]/l10n.yaml and returns where `flutter gen-l10n` writes.
///
/// Returns null when the project has no `l10n.yaml`, so a hand-written
/// `app_localizations.dart` in a project that does not use gen-l10n is left
/// alone. Defaults follow the Flutter tool: `arb-dir` is `lib/l10n`, `output-dir`
/// falls back to `arb-dir`, and `output-localization-file` is
/// `app_localizations.dart`.
L10nOutput? readL10nOutput(String projectPath) {
  final file = File(p.join(projectPath, 'l10n.yaml'));
  if (!file.existsSync()) return null;

  var arbDir = 'lib/l10n';
  String? outputDir;
  var baseFile = 'app_localizations.dart';

  final dynamic yaml = loadYaml(file.readAsStringSync());
  if (yaml is YamlMap) {
    final dynamic arb = yaml['arb-dir'];
    if (arb is String && arb.isNotEmpty) arbDir = arb;
    final dynamic out = yaml['output-dir'];
    if (out is String && out.isNotEmpty) outputDir = out;
    final dynamic outFile = yaml['output-localization-file'];
    if (outFile is String && outFile.isNotEmpty) baseFile = outFile;
  }

  return .new(dir: outputDir ?? arbDir, baseFile: baseFile);
}

bool _hasGeneratedMarker(String line) {
  final upper = line.toUpperCase();
  return _generatedHeaderMarkers.any(upper.contains);
}

/// Reads at most [maxBytes] from the start of [filePath], or null if it cannot
/// be opened. Generated markers sit at the very top, so a bounded read avoids
/// pulling a large generated file fully into memory just to skip it.
String? _readHead(String filePath, {int maxBytes = 4096}) {
  RandomAccessFile? raf;
  try {
    raf = File(filePath).openSync();
    final length = raf.lengthSync();
    final bytes = raf.readSync(length < maxBytes ? length : maxBytes);
    return utf8.decode(bytes, allowMalformed: true);
  } on FileSystemException {
    return null;
  } finally {
    raf?.closeSync();
  }
}

/// Decides whether a file should be skipped during modernization.
///
/// Exclusion sources, checked in order:
///   1. Generated-file suffixes and `build/` directory.
///   2. Generated localization output declared in `l10n.yaml`.
///   3. Glob patterns from [projectPath]/analysis_options.yaml `analyzer: exclude:`.
///   4. Ad-hoc CLI `--exclude` glob patterns.
///   5. A generated-code marker in the file's leading comment block.
final class FileFilter {
  FileFilter({
    required this.projectPath,
    List<String> excludePatterns = const [],
  }) : _excludeGlobs = [for (final pat in excludePatterns) .new(pat)],
       _l10nOutput = readL10nOutput(projectPath);

  /// Merges [projectPath]/analysis_options.yaml excludes with [cliExcludes].
  factory FileFilter.forProject(
    String projectPath, {
    List<String> cliExcludes = const [],
  }) => .new(
    projectPath: projectPath,
    excludePatterns: [
      ...readAnalysisOptionsExcludes(projectPath),
      ...cliExcludes,
    ],
  );

  final String projectPath;

  final List<Glob> _excludeGlobs;

  final L10nOutput? _l10nOutput;

  bool shouldSkip(String filePath) {
    if (isGeneratedFile(filePath)) return true;
    final rel = p.relative(filePath, from: projectPath).replaceAll(r'\', '/');
    if (_l10nOutput?.matches(rel) ?? false) return true;
    if (_excludeGlobs.any((g) => g.matches(rel))) return true;
    return hasGeneratedHeader(filePath);
  }
}

/// Where `flutter gen-l10n` writes its output, resolved from `l10n.yaml`.
///
/// [dir] is the output directory relative to the project root and [baseFile] is
/// the main localization file name; per-locale siblings are `<stem>_<locale>.dart`.
final class const L10nOutput({
  required final String dir,
  required final String baseFile,
}) {
  /// Whether [relativePath] (relative to the project root) is a file this
  /// localization run generates: the main file or one of its per-locale siblings.
  bool matches(String relativePath) {
    if (!p.equals(p.dirname(relativePath), dir)) return false;
    final name = p.basename(relativePath);
    if (name == baseFile) return true;
    final stem = baseFile.endsWith('.dart')
        ? baseFile.substring(0, baseFile.length - '.dart'.length)
        : baseFile;
    return name.startsWith('${stem}_') && name.endsWith('.dart');
  }
}
